import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Providers } from "./provider";

export const metadata: Metadata = {
  title: "Study Helper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <Providers>
          <body>
            {children}
          </body>
        </Providers>
      </StyledComponentsRegistry>
    </html>
  )
}
